org.gradle.jvmargs=-Xmx4608M
android.useAndroidX=true
android.enableJetifier=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.builder.sdkDownload=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
